### PR TITLE
Compile the crc test app

### PR DESCRIPTION
**Pull request by TimothyPMann**
I still think of the crc app as just a developer tool, so I didn't add
it to "progs"; you have to do "make crc" to compile it.  I did add
some minimal documentation in a comment.

I also updated crc.c and the Makefile so that I can compile the
package without warnings on both Ubuntu 20.04 (gcc version 9.3.0) and
Ubuntu 8.04 (gcc version 4.2.4) without warnings.  The crc.c change
was needed for gcc 9.3.0, and the Makefile change (-std=gnu99) was
needed for 4.2.4, which otherwise enforces an even older C standard.

### CODE REVIEW

**Review by qbarnes — COMMENTED** [review]
I don't get why the "-std=gnu99" was necessary.

I'm building regularly on Fedora 34 with gcc 11.2. so I spun up a VM with Ubuntu 20.04 with gcc 9.3.0 and built with the commit's changes but without  "-std=gnu99" Makefile change and it builds just fine for me.  Could you describe the compiler diagnostics you're seeing and with which compiler version that necessitated the "-std=gnu99" compiler flag?

**Comment by TimothyPMann** [comment]
I explained that in the commit message, but maybe I was too terse.
-std=gnu99 was needed to compile with the ancient gcc 4.2.4 on my Ubuntu 8.04
system that has my Catweasel cards plugged into it.  I use an old machine for
that so that I can use the CW MK1 ISA card in it, and I didn't want to try
updating it to a newer Linux distro.  Ubuntu 8.04 is so old that binaries
compiled with 20.04 won't run on it (and vice versa).

The default for gcc 4.2.4 is to enforce an even older standard than gnu99.
gnu99 is the newest it knows about, and it's new enough to make the current
source compile.

It's okay with me if you don't merge the gnu99; I can just keep that in my tree.

Without it I get these errors:

gcc -O3 -g -Wall -o cw2dmk cw2dmk.c catweasl.o cwpci.o -lpci -lz -lm
cw2dmk.c: In function ‘menu’:
cw2dmk.c:1534: error: ‘for’ loop initial declaration used outside C99 mode
cw2dmk.c: In function ‘parse_retries’:
cw2dmk.c:1573: error: ‘for’ loop initial declaration used outside C99 mode
cw2dmk.c:1619: error: redefinition of ‘i’
cw2dmk.c:1573: error: previous definition of ‘i’ was here
cw2dmk.c:1619: error: ‘for’ loop initial declaration used outside C99 mode
cw2dmk.c: In function ‘main’:
cw2dmk.c:1635: error: redeclaration of ‘i’ with no linkage
cw2dmk.c:1631: error: previous declaration of ‘i’ was here
cw2dmk.c:1635: error: ‘for’ loop initial declaration used outside C99 mode
cw2dmk.c:1798: error: ‘for’ loop initial declaration used outside C99 mode
make: *** [cw2dmk] Error 1
gcc -O3 -g -Wall -o dmk2cw dmk2cw.c catweasl.o cwpci.o -lpci -lz
dmk2cw.c: In function ‘main’:
dmk2cw.c:488: error: ‘for’ loop initial declaration used outside C99 mode
make: *** [dmk2cw] Error 1

On the other hand, crc.c with TEST defined (rightfully) gets warnings from gcc 9.3.0 without the changes I made to it in this commit. It does compile, but I don't believe in shipping code that gets compiler warnings.

$ gcc -O3 -g -Wall -DTEST -o crc crc.c
crc.c: In function ‘main’:
crc.c:81:14: warning: implicit declaration of function ‘strtol’ [-Wimplicit-function-declaration]
   81 |     preset = strtol(argv[1], NULL, 0);
      |              ^~~~~~
crc.c:91:39: warning: pointer targets in passing argument 2 of ‘calc_crc’ differ in signedness [-Wpointer-sign]
   91 |   printf("\n%04x\n", calc_crc(preset, buf, count));
      |                                       ^~~
      |                                       |
      |                                       char *
crc.c:63:25: note: expected ‘const unsigned char *’ but argument is of type ‘char *’
   63 |    unsigned char const *buf, int len)
      |    ~~~~~~~~~~~~~~~~~~~~~^~~

**Comment by qbarnes** [comment]
Ah, ok.  I didn't follow that thinking the problem was with Ubuntu 20.04, not Ubuntu 8.04.
